title: Rubynetti Blog
permalink: /:title/
baseurl: ""
external_links: [
    ['http://venezia86.it', 'venezia86.it'],
    ['https://simonini.netlify.com/', 'simonini.netlify.com'],
    ['https://github.com/rubynetti/blog', 'github.com/rubynetti/blog']
  ]

markdown: kramdown
theme: teatro-vecchio

languages: ['en','it']
google_analytics_account: UA-117679791-1
google_site_verification: BEZ89MJ3Dvac4sN7oi-dh8fiz6N4hIuygCnzObGCBA0
url: "https://rubynetti.netlify.com"

header_pages:
  - conventions.md

exclude:
  - Gemfile
  - Gemfile.lock
  - "*.gem"
  - "*.gemspec"
  - LICENSE.txt
  - README.md
  - Dockerfile
  - convenzioni.md
  - netlify.toml

exclude_from_localizations:
  - javascript
  - images
  - css
  - robots.txt
  - sitemap_index.xml
  - manifest.json
