[Settings]
  ID = "rubynetti"

# Redirect for first links
[[redirects]]
  from = "/docker/rails/2018/05/01/running-a-ror-container.html"
  to = "/running-a-ror-container.html"

[[redirects]]
  from = "/docker/rails/2018/04/16/rails-basic-dockerfile.html"
  to = "/rails-basic-dockerfile.html"

[[redirects]]
  from = "/docker/rails/2018/04/13/docker-rails-development.html"
  to = "/docker-rails-development.html"

[[redirects]]
  from = "/it/javascript/2018/04/17/vue-events.html"
  to = "/it/vue-events.html"

[[redirects]]
  from = "it/conventions/"
  to = "it/convenzioni-rails/"


 [[redirects]]
  from = "https://rubynetti.netlify.com/*"
  to = "https://www.rubynetti.it/:splat"
  status = 301
